# Generated by Django 5.0.4 on 2024-04-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0001_create_projects_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
            ],
            options={
                "db_table": "facts",
            },
        ),
    ]
