# Generated by Django 5.0.3 on 2024-03-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.CharField(max_length=50)),
                ("opens", models.TimeField()),
                ("closes", models.TimeField()),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "sites",
            },
        ),
    ]
