# Generated by Django 5.0.3 on 2024-03-28 23:23

from django.db import migrations, models

import disposal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        default="sites/default.jpg",
                        upload_to=disposal.models.upload_to,
                        verbose_name="Image",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sites",
            },
        ),
    ]
