# Generated by Django 5.0.3 on 2024-03-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposal", "0001_create_site_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("challenge", models.CharField(max_length=50)),
                ("experience", models.IntegerField()),
            ],
            options={
                "db_table": "challenges",
            },
        ),
    ]
