# Generated by Django 5.0.3 on 2024-03-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposal", "0002_create_challenges_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.CharField(max_length=50)),
            ],
        ),
    ]
