# Generated by Django 5.0.3 on 2024-04-02 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposal", "0003_create_dispositions_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bottle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("experience", models.IntegerField()),
                ("level", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bottles",
            },
        ),
    ]
