# Generated by Django 5.0.3 on 2024-04-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposal", "0004_create_bottles_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("goal_tons", models.CharField(max_length=50)),
                ("total_tons", models.CharField(max_length=50)),
                ("organizations", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "projects",
            },
        ),
    ]
