# Generated by Django 5.0.4 on 2024-04-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposal", "0004_create_bottles_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=50)),
                ("opens", models.TimeField()),
                ("closes", models.TimeField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="disposal.site"
                    ),
                ),
            ],
            options={
                "db_table": "schedules",
            },
        ),
    ]
