# Generated by Django 5.0.4 on 2024-04-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disposal", "0005_create_schedules_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="days_range",
            new_name="day",
        ),
    ]
