# Generated by Django 5.0.4 on 2024-04-21 22:59

import disposal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposal", "0005_create_projects_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                default="projects/default.jpg",
                upload_to=disposal.models.upload_to_projects,
                verbose_name="Image",
            ),
        ),
    ]
