# Generated by Django 5.0.4 on 2024-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disposal", "0005_create_schedules_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="latitude",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="site",
            name="longitude",
            field=models.CharField(default="0", max_length=50),
        ),
    ]
