name: Docker Image CI Admin

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
      - "app/**"
      - "backend/**"
      - .gitignore
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Project Code
        uses: actions/checkout@v3

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
          DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Change directory
        run: cd admin

      - name: Build the Docker Image
        run: docker build . --tag msosav/botellas-de-amor-admin:latest

      - name: Docker Push
        run: docker push msosav/botellas-de-amor-admin
