name: Formatter

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - "app/**"
      - "admin/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
        working-directory: backend

      - name: Black formatter
        run: |
          pipenv run black .
        working-directory: backend

      - name: Isort formatter
        run: |
          pipenv run isort .
        working-directory: backend

      - name: Prettier React Native
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
        working-directory: app
      - run: npm run format
        working-directory: app

      - name: Prettier React
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
        working-directory: admin
      - run: npm run format
        working-directory: admin

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix formatting
          skip_fetch: true
          branch: ${{ github.head_ref }}
